---
ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"


_grafana:
  cluster_name: jack-kr-grafana
  major_version: ""
  minor_version: ""
  patch_version: ""
  build_version: ""
  os_version: el9
  arch_type: x86_64
  bin_type: rpm
  db_name: pgsql_testdb
  db_user: jomoon
  user: postgres
  group: postgres
  db_password: 'changeme'
  home_dir: "/home/postgres"
  base_dir: "/root"
  domain: "jtest.pivotal.io"
  repo_url: ""
  download_url: ""
  download: true
  host_num: "{{ groups['all'] | length }}"
  base_path: /root
  # with_patroni_pkg: True
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"
  client:
    net:
      type: "virtual"              # Or Physical
      cores: 1
      ipaddr0: "192.168.0.19"
      ipaddr1: "192.168.1.19"
      ipaddr2: "192.168.2.19"
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05", "rk9-node06", "rk9-node07" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05" ]
  debug_opt: ""  # --debug


# go1.24.2.linux-amd64.tar.gz                  -  https://go.dev/dl/
_go:
  base_path: /root
  major_version: 1
  minor_version: 24
  patch_version: 2
  download: false
  download_url: "https://go.dev/dl"


# prometheus-3.2.1.linux-amd64.tar.gz          -  https://prometheus.io/download/
_prometheus:
  base_path: /root
  major_version: 3
  minor_version: 2
  patch_version: 1
  build_version: ""
  download: true
  download_url: "https://github.com/prometheus/prometheus/releases/download"


_exporter:
  base_path: /root
  jmx:
    version: "1.2.0"
    download_url: "https://github.com/prometheus/jmx_exporter/releases/download"
  postgres:
    version: "0.17.1"
    download_url: "https://github.com/prometheus-community/postgres_exporter/releases/download"
  cassandra:
    version: "2.3.8"
    download_url: "https://github.com/criteo/cassandra_exporter/releases/download"
  node:
    version: "1.9.1"
    download_url: "https://github.com/prometheus/node_exporter/releases/download"
  mysqld:
    version: "0.17.2"
    download_url: "https://github.com/prometheus/mysqld_exporter/releases/download"
  memcached:
    version: "0.15.2"
    download_url: "https://github.com/prometheus/memcached_exporter/releases/download"
  influxdb:
    version: "0.12.0"
    download_url: "https://github.com/prometheus/influxdb_exporter/releases/download"
  collectd:
    version: "0.7.0"
    download_url: "https://github.com/prometheus/collectd_exporter/releases/download"
  graphite:
    version: "0.16.0"
    download_url: "https://github.com/prometheus/graphite_exporter/releases/download"



common:
  sudo_user: jomoon
  sudo_group: jomoon
  sudo_user_home_dir: "/home/jomoon"
  pgsql_pkg_name: "vmware-postgres{{ pgsql.major_version }}"
  pgsql_bin_dir: "/opt/vmware/postgres/{{ pgsql.major_version }}/bin"
  # pgsql_pkg_name: pivotal-postgres


_ssl:
  ssl_dir: "/etc/grafana"
  ssl_days: 3660
  ssl_country: "KR"
  ssl_state: "Seoul"
  ssl_location: "Guro"
  ssl_organization: "VMware"
  ssl_organization_unit: "Tanzu"
  ssl_common_name: "jtest.pivotal.io"
  ssl_email: "jomoon@pivotal.io"
  enable: true


jdk:
  oss:
    install: true
    jvm_home: "/usr/lib/jvm"
    major_version: "1"
    minor_version: "8"
    patch_version: "0"
    # 1.8.0
    # 11.0.4
    # 17.0.2
  oracle:
    install: false
    jvm_home: "/usr/lib/jvm"
    major_version: "13"
    minor_version: "0"
    patch_version: "2"
    download: false


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

