---
- name: Stop and Disable Prometheus and Postgres_Exporter Services
  systemd:
    daemon_reexec: true
    daemon_reload: true
    name: "{{ item }}"
    enabled: false
    state: stopped
  ignore_errors: true
  register: stop_prometheus_services
  with_items:
    - prometheus


- name: Delete the Prometheus & Postgres_Exporter Config and Binary Files
  file: path={{ item.dest }} state=absent
  ignore_errors: true
  register: delete_config_files
  with_items:
    - { src: "prometheus.yml.j2",              dest: "/usr/local/etc/prometheus.yml" }
    - { src: "prometheus.systemd.j2",          dest: "/etc/systemd/system/prometheus.service" }
    - { src: "prometheus binary",              dest: "/usr/local/bin/prometheus" }
    - { src: "prometheus tar file",            dest: "/root/prometheus-{{ _prometheus.major_version }}.{{ _prometheus.minor_version }}.{{ _prometheus.patch_version }}.linux-amd64.tar.gz" }
    - { src: "prometheus directory",           dest: "/root/prometheus-{{ _prometheus.major_version }}.{{ _prometheus.minor_version }}.{{ _prometheus.patch_version }}.linux-amd64.tar.gz" }

