---
- name: Initialize PGDG Postgres Database Instance
  become_user: postgres
  shell: |
    source {{ _pgsql.base_dir }}/.bash_profile
    /usr/pgsql-{{ _pgsql.major_version }}/bin/initdb -D {{ _pgsql.base_dir }}/{{ _pgsql.major_version }}/data
  register: init_postgres_instance
  args:
    chdir: "{{ _pgsql.base_dir }}"
    executable: /bin/bash


- name: Create a Single Non-HA PGDG Postgres Database Server
  become_user: postgres
  shell: |
    source {{ _pgsql.base_dir }}/.bash_profile
    /usr/pgsql-{{ _pgsql.major_version }}/bin/postgres -D {{ _pgsql.base_dir }}/{{ _pgsql.major_version }}/data > {{ _pgsql.base_dir }}/{{ _pgsql.major_version }}/logfile 2>&1 &
  register: create_postgres_instance
  args:
    chdir: "{{ _pgsql.base_dir }}"
    executable: /bin/bash


- name: Verify that the psql of PGDG Postgres is Installed Properly
  become_user: postgres
  shell: |
    source {{ _pgsql.base_dir }}/.bash_profile
    /usr/pgsql-{{ _pgsql.major_version }}/bin/psql -c "select version()"
  register: verify_postgres_install
  args:
    chdir: "{{ _pgsql.base_dir }}"
    executable: /bin/bash


- name: Verify that the pg_ctl of PGDG Postgres is Installed Properly
  become_user: postgres
  shell: |
    source {{ _pgsql.base_dir }}/.bash_profile
    /usr/pgsql-{{ _pgsql.major_version }}/bin/pg_ctl -V
  register: verify_pg_ctl_install
  args:
    chdir: "{{ _pgsql.base_dir }}"
    executable: /bin/bash


- name: Insert the Line of Executable Binary Path into .bashrc for PostgreSQL {{ _pgsql.major_version }}
  become_user: postgres
  lineinfile:
    path: "{{ item }}"
    line: "export PATH=/usr/pgsql-{{ _pgsql.major_version }}/bin:$PATH"
  with_items:
    - "{{ _pgsql.base_dir }}/.bash_profile"
    - "{{ _pgsql.home_dir }}/.bash_profile"


- name: Grant User Access from Network Access for Access with Cert Authentication
  become_user: postgres
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  postgresql_pg_hba:
    dest: "{{ _pgsql.base_dir }}/{{ _pgsql.major_version }}/data/pg_hba.conf"
    contype: host
    users: all
    source: "{{ pgsql_network_range }}"
    databases: all
    method: trust


- name: Replace Database Directory
  become_user: postgres
  replace:
    path: "{{ _pgsql.base_dir }}/.bash_profile"
    regexp: '^(.*)PGDATA=(.*)$'
    replace: 'PGDATA=/{{ _pgsql.base_dir }}/{{ _pgsql.major_version }}/data'
    backup: yes


#- name: Change the Permissions on the Database Directory in {{ pgsql.base_dir }} Directory
#  become_user: postgres
#  file:
#    path: "{{ _pgsql.base_dir }}/{{ item }}"
#    state: directory
#    mode: 0750
#  register: change_data_directories_permission
#  with_items:
#    - "backups"
#    - "data"
#  when: pgsql.major_version|int >= 11


#- name: Change the Permissions on the Database Directory in {{ pgsql.base_dir }} Directory
#  become_user: postgres
#  file:
#    path: "{{ _pgsql.base_dir }}/{{ item }}"
#    state: directory
#    mode: 0700
#  register: change_data_directories_permission
#  with_items:
#    - "backups"
#    - "data"
#  when: pgsql.major_version|int < 11


#- name: Change the Permissions on the /tmp Directory
#  file:
#    path: /tmp
#    state: directory
#    mode: 0777
#  register: change_tmp_dir_permission


- name: Verify the Current State of Postgres
  become_user: postgres
  shell: |
    source {{ _pgsql.base_dir }}/.bash_profile
    /usr/pgsql-{{ _pgsql.major_version }}/bin/psql -c "\l"
  register: verify_postgres_state
  args:
    chdir: "{{ _pgsql.base_dir }}"
    executable: /bin/bash
- debug: msg={{ verify_postgres_state }}

