---
- name: Install MinIO Client ( mcli ) Package
  import_tasks: install-mcli-pkgs.yml


- name: Add Local MinIO Client Configuration
  shell: |
    mcli alias set myminio http://minio-api.jtest.pivotal.io minioadmin changeme --insecure
  register: add_local_minio_client_config
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ add_local_minio_client_config }}"
  register: add_local_minio_client_config


- name: Scraps MinIO Cluster Metrics
  shell: |
    echo "" >> /usr/local/etc/prometheus.yml
    echo "####  Scraps MinIO Cluster Metrics  ####" >> /usr/local/etc/prometheus.yml
    mcli admin prometheus generate myminio | sed 1d | sed -e '1,$ s/^/  /g' >> /usr/local/etc/prometheus.yml
  register: scrap_minio_cluster_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ scrap_minio_cluster_metrics }}"


- name: Scraps MinIO Nodes Metrics
  shell: |
    echo "" >> /usr/local/etc/prometheus.yml
    echo "####  Scraps MinIO Nodes Metrics  ####" >> /usr/local/etc/prometheus.yml
    mcli admin prometheus generate myminio node | sed 1d | sed -e '1,$ s/^/  /g' >> /usr/local/etc/prometheus.yml
  register: scrap_minio_nodes_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ scrap_minio_nodes_metrics }}"


- name: Scraps MinIO Buckets Metrics
  shell: |
    echo "" >> /usr/local/etc/prometheus.yml
    echo "####  Scraps MinIO Buckets Metrics  ####" >> /usr/local/etc/prometheus.yml
    mcli admin prometheus generate myminio bucket | sed 1d | sed -e '1,$ s/^/  /g' >> /usr/local/etc/prometheus.yml
  register: scrap_minio_buckets_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ scrap_minio_buckets_metrics }}"


- name: Scraps MinIO Resources Metrics
  shell: |
    echo "" >> /usr/local/etc/prometheus.yml
    echo "####  Scraps MinIO Resources Metrics  ####" >> /usr/local/etc/prometheus.yml
    mcli admin prometheus generate myminio resource | sed 1d | sed -e '1,$ s/^/  /g' >> /usr/local/etc/prometheus.yml
  register: scrap_minio_resources_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ scrap_minio_resources_metrics }}"


- name: Scraps MinIO Custom Buckets Metrics
  shell: |
    echo "" >> /usr/local/etc/prometheus.yml
    echo "####  Scraps MinIO Custom Buckets ( {{ item.bn }} ) Metrics  ####" >> /usr/local/etc/prometheus.yml
    mcli admin prometheus generate myminio api --bucket {{ item.bn }} --api-version v3 | \
    sed 1d | sed -e '1,$ s/^/  /g' | sed -e '1,$ s/minio-job-api/minio-job-api-{{ item.bn }}/g' \
    >> /usr/local/etc/prometheus.yml
  register: scrap_minio_custom_buckets_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  with_items:
    - { bn: "jtest-bucket01" }
    - { bn: "jtest-bucket02" }
    - { bn: "jtest-bucket03" }
- debug: msg="{{ scrap_minio_custom_buckets_metrics }}"


- name: Reload and Restart Prometheus Services
  systemd:
    daemon_reexec: true
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: restarted
  register: restart_prometheus_services
  with_items:
    - prometheus

