---

- name: Install MinIO Client ( mcli ) Package
  import_tasks: install-mcli-pkgs.yml


- name: Add Local MinIO Client Configuration
  shell: |
    mcli alias set myminio http://minio-api.jtest.pivotal.io minioadmin changeme --insecure
  register: add_local_minio_client_config
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ add_local_minio_client_config }}"
  register: add_local_minio_client_config


- name: Scraps MinIO Cluster Metrics
  shell: |
    echo "" >> /etc/prometheus/prometheus.yml
    echo "####  Scraps MinIO Cluster Metrics  ####" >> /etc/prometheus/prometheus.yml
    mcli admin prometheus generate myminio | sed 1d | sed -e '1,$ s/^/  /g' | sed '$ s/$/\n    honor_timestamps: false/' >> /etc/prometheus/prometheus.yml
  register: scrap_minio_cluster_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ scrap_minio_cluster_metrics }}"


- name: Scraps MinIO Nodes Metrics
  shell: |
    echo "" >> /etc/prometheus/prometheus.yml
    echo "####  Scraps MinIO Nodes Metrics  ####" >> /etc/prometheus/prometheus.yml
    mcli admin prometheus generate myminio node | sed 1d | sed -e '1,$ s/^/  /g' | sed '$ s/$/\n    honor_timestamps: false/' >> /etc/prometheus/prometheus.yml
  register: scrap_minio_nodes_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ scrap_minio_nodes_metrics }}"


- name: Scraps MinIO Buckets Metrics
  shell: |
    echo "" >> /etc/prometheus/prometheus.yml
    echo "####  Scraps MinIO Buckets Metrics  ####" >> /etc/prometheus/prometheus.yml
    mcli admin prometheus generate myminio bucket | sed 1d | sed -e '1,$ s/^/  /g' | sed '$ s/$/\n    honor_timestamps: false/' >> /etc/prometheus/prometheus.yml
  register: scrap_minio_buckets_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ scrap_minio_buckets_metrics }}"


- name: Scraps MinIO Resources Metrics
  shell: |
    echo "" >> /etc/prometheus/prometheus.yml
    echo "####  Scraps MinIO Resources Metrics  ####" >> /etc/prometheus/prometheus.yml
    mcli admin prometheus generate myminio resource | sed 1d | sed -e '1,$ s/^/  /g' | sed '$ s/$/\n    honor_timestamps: false/' >> /etc/prometheus/prometheus.yml
  register: scrap_minio_resources_metrics
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ scrap_minio_resources_metrics }}"


- name: Reload and Restart Prometheus Services
  systemd:
    daemon_reexec: true
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: restarted
  register: restart_prometheus_services
  with_items:
    - prometheus

