---
- name: Check the AlertManager Tar Files Already Exists
  stat: path={{ _alertmanager.base_path }}/{{ item }}
  register: check_tar_files
  with_items:
    - alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz


- name: Check the AlertManager Binary Files
  stat: path=/usr/local/bin/{{ item }}
  register: check_bin_files
  with_items:
    - alertmanager


- name: Copy the AlertManager Tar Files
  copy: src={{ item }} dest={{ _alertmanager.base_path }}/{{ item }} mode=0644 owner=root group=root
  register: copy_tar_files
  with_items:
    - alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
  when: not ( check_tar_files.results | map( attribute='stat.exists') ) is all


- name: Untar the AlertManager Tar Files
  shell: tar -C {{ _alertmanager.base_path }} -xf {{ _alertmanager.base_path }}/{{ item }}
  args:
    executable: /bin/bash
  with_items:
    - alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
  when: not ( check_bin_files.results | map( attribute='stat.exists') ) is all


- name: Copy Binary of the AlertManager into /usr/local/bin Directory
  shell: cp -f {{ _alertmanager.base_path }}/{{ item.src }} /usr/local/bin/{{ item.dest }}
  args:
    executable: /bin/bash
  with_items:
    - { src: "alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager", dest: "alertmanager" }
  when: not ( check_bin_files.results | map( attribute='stat.exists') ) is all


#- name: Copy the AlertManager Systemd File
#  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=644 force=yes
#  register: copy_systemd_file
#  with_items:
#    - { src: "alertmanager.yml.j2",              dest: "/usr/local/etc/alertmanager.yml" }
#    - { src: "alertmanager.systemd.j2",          dest: "/etc/systemd/system/alertmanager.service" }
#  when: not ( check_bin_files.results | map( attribute='stat.exists') ) is all


- name: Reload and Start AlertManager Services
  systemd:
    daemon_reexec: true
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: started
  register: start_alertmanager_services
  with_items:
    - alertmanager

