---
- name: Setup PGWatch2 Metrics Database As Default Datasource
  become_user: postgres
  shell: |
    psql -h localhost -U {{ item.user }} -d {{ item.db }} -f {{ item.file }}
  register: setup_metrics_database
  args:
    chdir: "{{ item.dir }}"
    executable: /bin/bash
  environment:
    PATH: "/opt/vmware/postgres/{{ pgsql.major_version }}/bin:{{ ansible_env.PATH }}"
  with_items:
    - { dir: "/etc/pgwatch2/bootstrap", file: "grafana_datasource.sql", user: "pgwatch2_grafana", db: "pgwatch2_grafana" }


- name: Add PGWatch2 Predefined Dashboards to Grafana
  shell: |
    /etc/pgwatch2/grafana-dashboards/import_all.sh
  async: 120
  poll: 5
  register: add_grafana_dashboard
  args:
    executable: /bin/bash
  environment:
    PATH: "/opt/vmware/postgres/{{ pgsql.major_version }}/bin:{{ ansible_env.PATH }}"

