---
- name: Check OS ( Grafana & Prometheus )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts for Package Name and List and Network Range
  import_tasks: set-facts.yml
  tags: testfact, install, uninstall, setup, remove, verify, create, delete, start, stop, enable, disable, config, check, add


- name: Add Prometheus System User
  import_tasks: add-sys-user.yml
  tags: add, install
  when: (( sysuser is defined and sysuser == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['monitor']


- name: Install Prometheus
  import_tasks: install-prometheus.yml
  tags: install, setup
  when: (( prometheus is defined and prometheus == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['monitor']


- name: Config MinIO Metrics
  import_tasks: config-minio-metrics.yml
  tags: config, setup, install
  when: ( minio is defined and minio == true ) and inventory_hostname in groups['monitor']


- name: Config NTP Server with Chrony
  import_tasks: ext/setup-chrony.yml
  tags: setup, install
  when: ( ntp is defined and ntp == true ) and inventory_hostname in groups['monitor']


- name: Uninstall Prometheus
  import_tasks: uninstall-prometheus.yml
  tags: uninstall, remove
  when: (( prometheus is defined and prometheus == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['monitor']


- name: Remove Prometheus System User
  import_tasks: remove-sys-user.yml
  tags: remove, uninstall
  when: (( sysuser is defined and sysuser == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['monitor']


